Traceback (most recent call last):
  File "D:/git_pros/git_chai/kmtronics_usb_relay_control/src/kmtronics_gui.py", line 250, in <module>
    vp_start_gui()
  File "D:/git_pros/git_chai/kmtronics_usb_relay_control/src/kmtronics_gui.py", line 30, in vp_start_gui
    kmtronics_gui_support.init(root, top)
  File "D:\git_pros\git_chai\kmtronics_usb_relay_control\src\kmtronics_gui_support.py", line 136, in init
    ap = ArduinoAppSupportClass()
  File "D:\git_pros\git_chai\kmtronics_usb_relay_control\src\kmtronics_gui_support.py", line 31, in __init__
    self.img_slide_on = PhotoImage(file=r'images\slide_on.png')
  File "C:\LegacyApp\Python36\lib\tkinter\__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\LegacyApp\Python36\lib\tkinter\__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "images\slide_on.png": no such file or directory
